### ISSUE TITLE
Provide a binary EXE release of the app

### ISSUE THREAD

**Issue by ijry** [paulirwin/JavaToCSharp#10]
i am a .net5 new user with vscode, i  try to run this project, but it failed.

**Comment by paulirwin** [comment]
Hi @ijry, that's a great idea and something I hope to do soon. I also want to do a .NET 5 upgrade anyways, as well as produce a NuGet package for the common library. I'll keep this issue open until I get that completed.

**Comment by paulirwin** [comment]
This is now complete as of v2.0.0.

**Comment by ijry** [comment]
excellent！
