### ISSUE TITLE
Improve options UI for smaller resolutions

### ISSUE THREAD

**Issue by paulirwin** [paulirwin/JavaToCSharp#103]
The options UI takes up way too much space on smaller monitors. We need to improve this UI.

**Comment by maximilien-noal** [comment]
Replace the theme with the default Fluent theme ? In compact mode.

https://docs.avaloniaui.net/docs/basics/user-interface/styling/themes/fluent => Changing theme density

But the Fluent theme looks worse on Mac.

There are a few 3rd party themes, like the Material theme:

https://github.com/AvaloniaCommunity/Material.Avalonia

**Comment by paulirwin** [comment]
I'm actually thinking about moving the options to a new window or modal behind i.e. a gear icon. I don't think the options need to be shown the entire time on the main screen, especially if users don't change them all that often.

**Comment by paulirwin** [comment]
Completed with #108
