### ISSUE TITLE
Arrays converts just Normal Data Type

### ISSUE THREAD

**Issue by rondeo-balos** [paulirwin/JavaToCSharp#11]
from this:
float[] localVertices;

to this:
float localVertices;

**Comment by paulirwin** [comment]
Thanks for reporting this! I'm in the middle of converting it to .NET 5 and working on trying to set up unit tests so that I can red/green issues like this. I'll look into this as part of that effort.

**Comment by paulirwin** [comment]
I can still reproduce this issue after the .NET 5 conversion and Roslyn upgrade so I hope to look at this soon.

**Comment by willibrandon** [comment]
@paulirwin - The issue here appears to be in [`TypeNameParser.Tokenize()`](https://github.com/paulirwin/JavaToCSharp/blob/7089b4140c9094148d32d0d2bc805aef393924ec/JavaToCSharp/TypeNameParser.cs#L52). The brackets are getting dropped while parsing the type type name because the regex [`_tokenizePattern`](https://github.com/paulirwin/JavaToCSharp/blob/7089b4140c9094148d32d0d2bc805aef393924ec/JavaToCSharp/TypeNameParser.cs#L21) is not matching the square brackets, only angle brackets.

**Comment by paulirwin** [comment]
@willibrandon Would you like to tackle this one? I promise not to take it from you this time 😆

**Comment by willibrandon** [comment]
I would love to.

**Comment by willibrandon** [comment]
@paulirwin - Just so I'm clear on the problem I would like to think about it out loud first.

JavaToCSharp would like to add support for declaration of array variables, specifically when the empty square brackets `[]` appear as part of the the type at the beginning of the declaration.

For example:

`float[] localVertices;` should covert to `float[] localVertices;`

In my testing, when the empty square brackets `[]` appear as part of the declarator and follow the variable's _identifier_, this appears to already work as expected. So I believe we are good with this scenario.

For example:

`float localVerticies[];` currently converts to `float[] localVertices;`

If my above assumptions are correct then I will submit a PR that will add support for declaration of array variables when the empty square brackets `[]` appear as part of the the type at the beginning of the declaration.

**Comment by paulirwin** [comment]
I completely forgot that Java supports declaring an array with the brackets following the identifier! Sounds like you're on the right track.

From a quick google, it also looks like this monstrosity is valid syntax, so worth a test as well:
```java
float []localVertices;
```

**Comment by paulirwin** [comment]
Turns out the `float []localVertices;` is valid syntax in C# too (sigh), but I don't think we need to necessarily translate it that way. I'm fine with making all array declarations use the `float[] localVertices;` syntax.

**Comment by paulirwin** [comment]
Unit tests would be great! Since this prototype I created many years ago has started gaining some steam, moving in a more mature direction would be awesome.

**Comment by willibrandon** [comment]
Sorry for the delay on this. In-laws are in town plus the holiday weekend coming up has chewed into some of my free time. I should get a chance to submit a PR at some point this weekend.
