### ISSUE TITLE
Update javaparser

### ISSUE THREAD

**Issue by paulirwin** [paulirwin/JavaToCSharp#12]
Update javaparser to support newer language features. Need to confirm the licensing changes are compatible.

**Comment by VahidN** [comment]
It seems due to using the generics in the new  javaparser's API, it's not possible to use its IKVM output anymore. [More info](https://github.com/ikvm-revived/ikvm/issues/299)

**Comment by GeorgeS2019** [comment]
@VahidN 
@viceice 
@paulirwin 

The latest ikvm-revived with .NET Core could improve the performance of the created javaparser.dll

**Comment by paulirwin** [comment]
I'm currently working on this item 🙂 Also working on a solution for running on a M1 Mac.

**Comment by viceice** [comment]
with new ikvm you can use the mavenreference, so you even don't need to provide tha jar file

https://central.sonatype.com/artifact/com.github.javaparser/javaparser-core/

**Comment by paulirwin** [comment]
Yep, now that I've brushed the dust off this project and got it running on .NET 6, this will be my next step. Thanks!

**Comment by paulirwin** [comment]
MavenReference with IKVM.Maven.SDK doesn't seem to be working for me, not sure why. But trying to get it working with a straight IkvmReference is a bit of a nightmare. @VahidN was very right above. Not having generics and having everything be `Optional<T>` is going to involve a lot of casting or pattern matching. Not impossible, but a lot of work. I'll figure out a way to get it done though.

**Comment by jonathanlocke** [comment]
What version of the Java language will the new release support?

**Comment by paulirwin** [comment]
@jonathanlocke Also if there are specific language features that you prioritize supporting, please feel free to file a separate issue so I can keep track of them and not miss anything important.

**Comment by paulirwin** [comment]
FYI, I have this building and all unit tests are passing. I'll be doing a bit more testing to make sure there aren't any significant regressions (I'm sure there might be some...) before pushing it up.

**Comment by paulirwin** [comment]
This is now in master. If someone can help me test this that would be appreciated. Please pull master, build, and try to run on your examples. If anything breaks, please submit an issue. Thanks!

**Comment by paulirwin** [comment]
Note that newer language features are not yet supported; follow #53 for progress.
