### ISSUE TITLE
Add a unit test project

### ISSUE THREAD

**Issue by willibrandon** [paulirwin/JavaToCSharp#13]
It would be nice if we had unit tests to make sure we don't regress while making new changes and to take the JavaToCSharp in a more mature direction _as mentioned by @paulirwin in https://github.com/paulirwin/JavaToCSharp/issues/11#issuecomment-869962821_.

I believe Microsoft is using xUnit for most of their projects. I have some experience with xUnit from working on those projects but also have experience with MSTest and have read a book on NUnit. Any thoughts on which test framework should be used would be greatly appreciated.

**Comment by paulirwin** [comment]
I prefer xunit, thanks!

**Comment by OJacot-Descombes** [comment]
We do not have complex scenarios here. Arrange: input string (Java). Act: parse(). Assert: output string (C#) == "expected string". So, it really doesn't matter.

**Comment by paulirwin** [comment]
For testing large files like we would be doing for full Java and C# code examples, I've found this helpful, where you can have your inputs and expected values be embedded resources, with xUnit's `[Theory]` attribute: https://patriksvensson.se/2017/11/using-embedded-resources-in-xunit-tests/
