### ISSUE TITLE
Each comment written to C# code includes all previous comments

### ISSUE THREAD

**Issue by malcolmbss** [paulirwin/JavaToCSharp#131]
I just downloaded and tried converting my first java file.  But I'm encountering a problem.  When the first comment is encountered, it is written to the C# file.  When the next comment is encountered, the first comment and the second comment are both written to the C# file.  Then on the third java comment, the first, second, and third comment are all written.  By the end of the java file each java comment causes the possibly hundreds of previous comments to all be written as a huge block time after time.  There's nothing unique about the source java file as far as I know.  I'm pretty proficient in both java and c#.  If you can tell me where to look in the code for where comments are being added to the c# file, I can do some debug and hopefully figure this out.  Thanks.

**Comment by malcolmbss** [comment]
Here's an example java input and converted cs output showing the comment problem described above.
[JavaToCSharp issue 131 Example.zip](https://github.com/user-attachments/files/17987227/JavaToCSharp.issue.131.Example.zip)

**Comment by javiertuya** [comment]
@malcolmbss This PR https://github.com/paulirwin/JavaToCSharp/pull/126 (which is currently awaiting review) will solve the issue (it happens when a java class extends a class or implements an interface). Hope it will be merged soon.
