### ISSUE TITLE
Escaped string characters are getting extra backslashes

### ISSUE THREAD

**Issue by paulirwin** [paulirwin/JavaToCSharp#20]
Java string of `"\\R"` is getting translated to `"\\\\R"`.

**Comment by skpandey885** [comment]
Can I Fix This One?

**Comment by paulirwin** [comment]
@skpandey885 Absolutely! PRs welcome.

**Comment by skpandey885** [comment]
Can You Explain a Bit more..What I Have To do? I am Beginner So I need Your Help, Sir!

**Comment by paulirwin** [comment]
I'd recommend starting with a unit test that tests what the behavior should be. This test will fail, of course. (This is known as red/green testing.) Then debug and step through the code to see if you can find where the issue is. I believe you may start looking into the `StringLiteralExpressionVisitor` class. Most likely code needs to be added to fix this issue. Also please make sure this works for character literals as well (i.e. `'\n'` and `'\\'`).
