### ISSUE TITLE
Option to turn off javadoc comment translation

### ISSUE THREAD

**Issue by paulirwin** [paulirwin/JavaToCSharp#21]
Would like a GUI/CLI option to turn off javadoc comment translation. Can be enabled by default.

**Comment by willibrandon** [comment]
I believe I have this working locally but am curious what the purpose is?

Also, just so I'm clear on the requirements, am I correct about the following types of comments in Java?

- Normal comment
`// comment`

- Block comment
`/* comment */`

- JavaDoc comment
`/** comment */`

**Comment by paulirwin** [comment]
As for the purpose, it's a nice-to-have, sometimes the comments can get in the way IMHO. Also many times they refer to other Java code so you either have irrelevant/incorrect comments or you have to go through and update them. There's also a syntax bug with javadoc translation currently for things like `@author` and such, that I would honestly rather turn off at the moment than fix. 

And you are correct about the comment syntax.

**Comment by paulirwin** [comment]
Option to disable comment translation entirely has been added. Not sure we need a Javadoc-specific option at this time.
