### ISSUE TITLE
JavaDoc Implementation

### ISSUE THREAD

**Issue by ChristopherHaws** [paulirwin/JavaToCSharp#3]
So, I am working on implementing comments and have very basic comment support working. I started working on parsing JavaDoc's to try and convert them to XML Documentation comments, however I am not sure if I should continue trying to create my own parser or if I should try to use the builtin Java implementation of the Doclet API.

The only reason I am hesitant is because the Docklet API is in tools.jar which is close to 18MB and has a lot more functionality than I need.

https://docs.oracle.com/javase/8/docs/jdk/api/javadoc/doclet/com/sun/javadoc/package-summary.html

Any thoughts?

**Comment by paulirwin** [comment]
Among the scariest phrases in computer science has to be "create my own parser" :-) 

Maybe we could set up a build step to pull down the jar from the internet so that it doesn't have to be checked into the repo?

**Comment by ChristopherHaws** [comment]
That's an idea. Maybe we could make nuget packages out of them and publish them on nuget.org. Should be simple enough to do. What do you think?

**Comment by paulirwin** [comment]
Given Oracle's history, I'd be worried about publishing that on NuGet. Is there an OpenJDK version of the tools.jar?

**Comment by ChristopherHaws** [comment]
It looks like it is in their [source control](http://hg.openjdk.java.net/javadoc-next/api/langtools/file/5d77a94600d8/src/jdk.compiler/share/classes/com/sun/source). 

[Here are Windows binaries of OpenJDK](https://github.com/ojdkbuild/ojdkbuild) that someone is maintaining. It has tools.jar in the download.

**Comment by ChristopherHaws** [comment]
Even better, I think that the API's I need might already be in the solution! IKVM has a dll called `IKVM.OpenJDK.Tools` and it looks like it is tools.jar as a .NET library... :)

**Comment by paulirwin** [comment]
This is mostly complete thanks to @OJacot-Descombes
