### ISSUE TITLE
How to launch the CLI Version?

### ISSUE THREAD

**Issue by TheBalkanDev** [paulirwin/JavaToCSharp#36]

**Comment by alibrahimzada** [comment]
Hi Paul,
Running `dotnet build` in the repo root gives the following error for me:

```
/Users/user/.nuget/packages/ikvm.msbuild/8.6.2/buildTransitive/netstandard2.0/IKVM.MSBuild.Tasks.targets(25,9): error MSB4044: The "IkvmGetReferenceAssemblies" task was not given a value for the required parameter "ToolPath". [/Users/user/Documents/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
```

Any ideas?

**Comment by paulirwin** [comment]
@alibrahimzada Are you on Arm64 by chance? That architecture is unfortunately not yet supported. I need to try out the latest IKVM 8.7 prerelease builds now that they are available to see if that resolves the issue.

**Comment by alibrahimzada** [comment]
Yes I am on Arm64. Thank you so much.
