### ISSUE TITLE
Update to new IKVM 8.2+ version

### ISSUE THREAD

**Issue by viceice** [paulirwin/JavaToCSharp#39]
There is a new preview of IKVM, which supports `net461+` and `netcoreapp3.1+`, it's working fine for us.

- https://github.com/ikvm-revived/ikvm/releases
- https://github.com/visualon/featureide.net

**Comment by GeorgeS2019** [comment]
@viceice 

This is NOT FEASIBLE for this Project purpose !!!! 

This e.g .NET6 support IKVM does not support AWT
- [headless AWT](https://github.com/ikvm-revived/ikvm/issues/298)
- UI

**Comment by viceice** [comment]
i don't need at or UI, that will be build with dotnet or any web framework 🙃

**Comment by paulirwin** [comment]
I'm working on this now as well as .NET 6 support.

Currently working through the workaround for this error https://github.com/ikvmnet/ikvm/issues/394

cc @wasabii

**Comment by paulirwin** [comment]
This is nearly complete, as well as .NET 6 support! Coming very soon.

**Comment by paulirwin** [comment]
This is now complete as of latest master, and once I get a few more things in there I'll prepare a proper 3.0 release.
