### ISSUE TITLE
How JavaToCSharp complement the active Ikvm project?

### ISSUE THREAD

**Issue by GeorgeS2019** [paulirwin/JavaToCSharp#44]
Although [ikvm ](https://github.com/ikvm-revived/ikvm/issues/301)could NOW compile java project, it does not RIGHT NOW support AWT which JavaToCSharp could right NOW

**Comment by paulirwin** [comment]
Hi, the two projects serve different tasks. IKVM is to provide a Java runtime on .NET, while this project is for syntactic conversion of Java language code text to C# language code text to facilitate i.e. porting Java code to .NET without needing a Java runtime. JavaToCSharp in fact uses IKVM to do some of its work. They are orthogonal, not competing, projects. I hope you will enjoy using both projects as needed.

There is nothing to be done for this open issue, so closing it.
