### ISSUE TITLE
Octal is not converted correctly

### ISSUE THREAD

**Issue by adipose** [paulirwin/JavaToCSharp#45]
In Java, as in C, you can specify an octal integer by prefixing with a zero (https://www.geeksforgeeks.org/java-program-to-illustrate-the-usage-of-octal-integer/).

077 = 0x3F = 63

JavaToCSharp preserves the original 077 text.

The problem is that CSharp does not support octal integers, leading to 077 being treated as 77L (https://www.ecma-international.org/wp-content/uploads/ECMA-334_6th_edition_june_2022.pdf 6.4.5.3).

**Comment by paulirwin** [comment]
Fixed in trunk for the upcoming 3.0 release, thanks for bringing this to my attention!

**Comment by adipose** [comment]
Awesome thank you!
