### ISSUE TITLE
Update tools and packages

### ISSUE THREAD

**Issue by Adrian-Devries** [paulirwin/JavaToCSharp#46]
[UpdatePackagesAndTools.patch](https://github.com/paulirwin/JavaToCSharp/files/11857144/UpdatePackagesAndTools.patch)
Update tools and packages: After applying the patch, the file Lib/javaparser-core-3.0.0-SNAPSHOT.jar needs to be processed with the new [IKVM](https://github.com/ikvmnet/ikvm/releases/tag/8.5.2) compiler to create a new DLL. Afterwards the code compiles without any errors or warnings.

**Comment by paulirwin** [comment]
I appreciate the patch, but I'd prefer changes as PRs for future reference. This is effectively now complete for .NET 6 LTS in master, and all NuGet packages have been updated. We are also now building the javaparser dll with IkvmReference.
