### ISSUE TITLE
Switch from snapshot to officially published releases of JavaParser

### ISSUE THREAD

**Issue by Adrian-Devries** [paulirwin/JavaToCSharp#47]
[alpha1.patch](https://github.com/paulirwin/JavaToCSharp/files/11857162/alpha1.patch)
Currently, the code is using a custom artifact of JavaParser, i.e., Lib/javaparser-core-3.0.0-SNAPSHOT.jar. Of course, there is an officially published release: [javaparser-core-3.0.0-alpha.1.jar](https://repo1.maven.org/maven2/com/github/javaparser/javaparser-core/3.0.0-alpha.1/javaparser-core-3.0.0-alpha.1.jar). For consistency, the officially published release should be used.

After applying the patch and after processing the JAR file javaparser-core-3.0.0-alpha.1.jar with the new [IKVM](https://github.com/ikvmnet/ikvm/releases/tag/8.5.2), the code compiles without any errors or warnings.

**Comment by Adrian-Devries** [comment]
The same is the case for the release [javaparser-core-3.0.0-alpha.2.jar](https://repo1.maven.org/maven2/com/github/javaparser/javaparser-core/3.0.0-alpha.2/javaparser-core-3.0.0-alpha.2.jar).
[alpha2.patch](https://github.com/paulirwin/JavaToCSharp/files/11857177/alpha2.patch)

**Comment by Adrian-Devries** [comment]
From the release [javaparser-core-3.0.0-alpha.3.jar](https://repo1.maven.org/maven2/com/github/javaparser/javaparser-core/3.0.0-alpha.3/javaparser-core-3.0.0-alpha.3.jar) and up, any attempt to compile the code runs into errors. So, changes are required to use at least [javaparser-core-3.0.0.jar](https://repo1.maven.org/maven2/com/github/javaparser/javaparser-core/3.0.0/javaparser-core-3.0.0.jar). Note that in the meantime [javaparser-core-3.25.3.jar](https://repo1.maven.org/maven2/com/github/javaparser/javaparser-core/3.25.3/javaparser-core-3.25.3.jar) has been published (cf. [https://github.com/javaparser/javaparser/releases/latest](https://github.com/javaparser/javaparser/releases/latest)).
[alpha3.patch](https://github.com/paulirwin/JavaToCSharp/files/11857199/alpha3.patch)

**Comment by paulirwin** [comment]
@Adrian-Devries Thanks for the info, this is already being tracked as #12, so closing this as duplicate. There are a few IKVM things standing in the way at the moment for me, working through those. Thanks!
