### ISSUE TITLE
Cannot Build on macOS Arm64

### ISSUE THREAD

**Issue by alibrahimzada** [paulirwin/JavaToCSharp#81]
Running `dotnet build` in the repo root gives the following error for me:

```
/Users/user/.nuget/packages/ikvm.msbuild/8.6.2/buildTransitive/netstandard2.0/IKVM.MSBuild.Tasks.targets(25,9): error MSB4044: The "IkvmGetReferenceAssemblies" task was not given a value for the required parameter "ToolPath". [/Users/user/Documents/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
```
Any ideas?

**Comment by paulirwin** [comment]
@alibrahimzada Please check out the feature/ikvm-8.7 branch which uses a prerelease version of IKVM with arm64 support, and let me know if that works for you. I do not want to merge this into master until 8.7 is out of prerelease, but early feedback is appreciated. Thanks!

**Comment by alibrahimzada** [comment]
Hi Paul,
I wanted to confirm this new branch now works on macOS arm64. You may want to change all `<TargetFramework>`  to `net7.0` because right now there is an incosistency between `.csproj` in `JavaToCSharp.Tests` and other ones (`JavaToCSharp`, `JavaToCSharpCli`, `JavaToCSharpGui`). I manually changed all `net6.0` to `net7.0` and now the GUI and CLI works fine.

Thank you.

**Comment by paulirwin** [comment]
I'm not sure what you mean, the CLI and GUI work on macOS Arm64 for me without making that modification. What issue were you having?

**Comment by alibrahimzada** [comment]
Alright never mind. There was an inconsistency on my end. Thank you for opening this branch, Paul.
